default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: postgres
  password: postgres
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: takirails_dev

test:
  <<: *default
  database: takirails_test

production:
  <<: *default
  database: takirails_prod
